#!/usr/bin/env bash
# setup_sahmi_home.sh — sahmi.ae becomes the desk home page + adds shine.
# =======================================================================
# Layout after this script:
#   sahmi.ae / www      -> home page (links to every system), gate sign-in
#   trader.sahmi.ae     -> Combo Trader           (127.0.0.1:5050)
#   paper.sahmi.ae      -> SPX 0DTE paper system  (127.0.0.1:5250)
#   shine.sahmi.ae      -> new stock system trial (127.0.0.1:${SHINE_PORT})
# One sign-in (the existing gate) covers all four hosts.
#
# Run AFTER setup_sahmi_login.sh, on the hub:
#     cd ~/spx-paper-trader && git pull
#     cd deploy && sudo bash setup_sahmi_home.sh
# Then in Cloudflare DNS for sahmi.ae add:  A  shine  -> 209.38.241.101,
# Proxied (orange) like the others.
#
# SHINE_PORT defaults to 6050 (the hub's beta platform, logicon-beta).
# Different backend?  sudo SHINE_PORT=XXXX bash setup_sahmi_home.sh

set -euo pipefail
[ "$(id -u)" = 0 ] || { echo "run with sudo"; exit 1; }

DOMAIN="sahmi.ae"
SHINE_PORT="${SHINE_PORT:-6050}"
REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
APP_DIR="/opt/logicon/spx-paper-trader"
CERT_DIR="/etc/nginx/sahmi-certs"
CONF="/etc/nginx/sites-available/sahmi.conf"
HOME_ROOT="${APP_DIR}/static/home"

command -v nginx >/dev/null || { echo "nginx not found"; exit 1; }
[ -f "$CERT_DIR/sahmi.crt" ] || { echo "run setup_sahmi_nginx.sh first"; exit 1; }
[ -f "$APP_DIR/gate_credentials.json" ] || { echo "run setup_sahmi_login.sh first (no gate credentials)"; exit 1; }
LOGICON_USER="${LOGICON_USER:-$(stat -c %U /opt/logicon/combo-trader 2>/dev/null || echo root)}"
id "$LOGICON_USER" >/dev/null 2>&1 || LOGICON_USER=root

echo "== 1/2 Sync app (home page files) =="
rsync -a --exclude '.git' --exclude '__pycache__' --exclude 'data' \
      --exclude 'gate_credentials.json' --exclude 'gate_secret' \
      "$REPO_DIR/" "$APP_DIR/"
chown -R "$LOGICON_USER":"$LOGICON_USER" "$APP_DIR"
[ -f "$HOME_ROOT/index.html" ] || { echo "home page missing at $HOME_ROOT"; exit 1; }

echo "== 2/2 nginx: home + trader + paper + shine (shine -> :${SHINE_PORT}) =="
[ -f "$CONF" ] && cp "$CONF" "${CONF}.bak.$(date +%s)"

# Shared per-host snippets (auth_request gate + login redirect)
GATE_LOCS=$(cat <<'G'
    location = /gate/check {
        internal;
        proxy_pass http://127.0.0.1:5260;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header X-Original-URI $request_uri;
    }
    location /gate/ {
        proxy_pass http://127.0.0.1:5260;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location @login {
        return 302 /gate/login?next=$request_uri;
    }
G
)

proxy_block() {  # $1 = upstream port, $2 = websocket yes/no
  cat <<P
    location / {
        auth_request /gate/check;
        error_page 401 = @login;
        proxy_pass http://127.0.0.1:$1;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 120s;
    }
P
}

{
cat <<EOF
# sahmi.ae — Logicon desk (generated by spx-0DTE-v1 deploy/setup_sahmi_home.sh)
# home (static) + trader :5050 + paper :5250 + shine :${SHINE_PORT}.
# Auth: one gate sign-in (127.0.0.1:5260) covers all hosts. Public TLS at
# Cloudflare (Proxied + Full); the self-signed cert covers CF->origin only.
# The client portal's own nginx sites are untouched.

server {
    listen 80;
    listen 443 ssl;
    server_name ${DOMAIN} www.${DOMAIN};
    ssl_certificate     ${CERT_DIR}/sahmi.crt;
    ssl_certificate_key ${CERT_DIR}/sahmi.key;

${GATE_LOCS}
    location / {
        auth_request /gate/check;
        error_page 401 = @login;
        root ${HOME_ROOT};
        index index.html;
        try_files \$uri /index.html;
    }
}

server {
    listen 80;
    listen 443 ssl;
    server_name trader.${DOMAIN};
    ssl_certificate     ${CERT_DIR}/sahmi.crt;
    ssl_certificate_key ${CERT_DIR}/sahmi.key;

${GATE_LOCS}
$(proxy_block 5050)
}

server {
    listen 80;
    listen 443 ssl;
    server_name paper.${DOMAIN};
    ssl_certificate     ${CERT_DIR}/sahmi.crt;
    ssl_certificate_key ${CERT_DIR}/sahmi.key;

${GATE_LOCS}
$(proxy_block 5250)
}

server {
    listen 80;
    listen 443 ssl;
    server_name shine.${DOMAIN};
    ssl_certificate     ${CERT_DIR}/sahmi.crt;
    ssl_certificate_key ${CERT_DIR}/sahmi.key;

${GATE_LOCS}
$(proxy_block ${SHINE_PORT})
}
EOF
} > "$CONF"

ln -sf "$CONF" /etc/nginx/sites-enabled/sahmi.conf
nginx -t
systemctl reload nginx

cat <<EOF

============================================================
DONE. Layout is now:
    https://${DOMAIN}          -> desk home page (links to all)
    https://trader.${DOMAIN}   -> Combo Trader
    https://paper.${DOMAIN}    -> SPX 0DTE paper system
    https://shine.${DOMAIN}    -> new stock system (:${SHINE_PORT})

One thing left, in Cloudflare DNS for ${DOMAIN}:
    add   A   shine   209.38.241.101   Proxied (orange)

Same sign-in everywhere; sign out at /gate/logout.
If shine shows "502 Bad Gateway", nothing is listening on
:${SHINE_PORT} yet — start the trial system, or re-run with
SHINE_PORT=<port> to point at the right one.
============================================================
EOF
